title: Nora Goldfine
logo: /assets/img/bitmoji_smile.png
theme: jekyll-theme-minimal

# (another formatting option)
#title: Nora Goldfine
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
