title: Nora Goldfine
theme: jekyll-theme-minimal
- title: Education
  url: https://ngoldfine.github.io/education/
- title: Experience
  url: https://ngoldfine.github.io/experience/
- title: Projects
  url: https://ngoldfine.github.io/projects/

# (another formatting option)
#title: Nora Goldfine
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
